lakehouse:
  ceph:
    ceph_endpoint: ${CEPH_ENDPOINT}
    ceph_access_key: ${CEPH_ACCESS_KEY}
    ceph_secret_key: ${CEPH_SECRET_KEY}
    ssl_enabled: false
    path_style_access: true #Required for Ceph RGW
    s3a_attempts_max: 3,
    s3a_connection_timeout: 300000
    bucket_checkpoints: ${CEPH_BUCKET_CHECKPOINTS},
    bucket_lakehouse: ${CEPH_BUCKET_LAKEHOUSE}
  hive_metastore:
    hive_uri: ${HIVE_URI}
  iceberg:
    write.format.default: parquet
    write.parquet.compression-codec: zstd
    write.target-file-size-bytes: "134217728" # 128MB
    write.distribution-mode: hash
    write.metadata.delete-after-commit.enabled: "true"
    write.metadata.previous-versions-max: "20"
    format-version: "2"
kafka:
  bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS}
  user: ${KAFKA_USER}
  password: ${KAFKA_PASSWORD}
  security_protocol: "SASL_PLAINTEXT"
  sasl_mechanism: "SCRAM-SHA-256"
  secure: false