class StringConstants:
    CEPH_ENDPOINT = "CEPH_ENDPOINT"
    CEPH_ACCESS_KEY = "CEPH_ACCESS_KEY"
    CEPH_SECRET_KEY = "CEPH_SECRET_KEY"
    CEPH_REGION = "CEPH_REGION"
    CEPH_SSL_ENABLED = "CEPH_SSL_ENABLED"

    KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS"
    KAFKA_USER = "KAFKA_USER"
    KAFKA_PASSWORD = "KAFKA_PASSWORD"

    TRANSFORM_PHONE_NUMBER = "transform_phone_number"

    SPARK_SQL_SHUFFLE_PARTITIONS = "spark.sql.shuffle.partitions"
    SPARK_DEFAULT_PARALLELISM = "spark.default.parallelism"
    MIN_BATCHES_TO_RETAIN = "spark.sql.streaming.minBatchesToRetain"
    NO_DATA_PROGRESS_EVENT_INTERVAL = "spark.sql.streaming.noDataProgressEventInterval"
    NO_DATA_MICRO_BATCHES = "spark.sql.streaming.noDataMicroBatches.enabled"
    SPARK_STREAMING_STOP_GRACE_FULLY_ON_SHUTDOWN = "spark.streaming.stopGracefullyOnShutdown"
    CLEANER_CHECKPOINTS = "spark.cleaner.referenceTracking.cleanCheckpoints"
    MAX_TO_STRING_FIELDS = "spark.sql.debug.maxToStringFields"

    SPARK_HADOOP_FS_S3A_IMPL = "spark.hadoop.fs.s3a.impl"
    HADOOP_FS_S3A_FILE_SYSTEM = "org.apache.hadoop.fs.s3a.S3AFileSystem"
    S3A_ENDPOINT = "spark.hadoop.fs.s3a.endpoint"
    S3A_PATH_STYLE_ACCESS = "spark.hadoop.fs.s3a.path.style.access"
    ACCESS_KEY = "spark.hadoop.fs.s3a.access.key"
    SECRET_KEY = "spark.hadoop.fs.s3a.secret.key"
    S3A_AWS_CREDENTIALS_PROVIDER = "spark.hadoop.fs.s3a.aws.credentials.provider"
    S3A_SIMPLE_AWS = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    S3A_IMPL_DISABLE_CACHE = "spark.hadoop.fs.s3a.impl.disable.cache"
    S3A_CONNECTION_SSL_ENABLED = "spark.hadoop.fs.s3a.connection.ssl.enabled"
    S3A_ATTEMPTS_MAXIMUM = "spark.hadoop.fs.s3a.attempts.maximum"
    S3A_CONNECTION_TIMEOUT = "spark.hadoop.fs.s3a.connection.timeout"
    S3A_CONNECTION_ESTABLISH_TIMEOUT = "spark.hadoop.fs.s3a.connection.establish.timeout"

    KAFKA = "kafka"
    BOOTSTRAP_SERVERS = "kafka.bootstrap.servers"
    STARTING_OFFSETS = "startingOffsets"
    SUBSCRIBE = "subscribe"
    FAIL_ON_DATA_LOSS = "failOnDataLoss"
    KAFKA_KEY_DESERIALIZER = "kafka.key.deserializer"
    KAFKA_VALUE_DESERIALIZER = "kafka.value.deserializer"
    STRING_DESERIALIZER = "org.apache.kafka.common.serialization.StringDeserializer"
    KAFKA_MAX_OFFSET_PER_TRIGGER = "maxOffsetsPerTrigger"
    KAFKA_METADATA_MAX_AGE_MS = "kafka.metadata.max.age.ms"
    SECURITY_PROTOCOL = "kafka.security.protocol"
    SASL_MECHANISM = "kafka.sasl.mechanism"
    KAFKA_SASL_JAAS_CONFIG = "kafka.sasl.jaas.config"

    # Iceberg Config
    ICEBERG_CATALOG = "bronze"
    ICEBERG_FORMAT = "iceberg"
    ICEBERG_EXTENSIONS = "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
    ICEBERG_SPARK_CATALOG = "org.apache.iceberg.spark.SparkCatalog"
    ICEBERG_S3_FILE_IO = "org.apache.iceberg.aws.s3.S3FileIO"

    ICE_WRITE_FORMAT_DEFAULT = "write.format.default"
    ICE_PARQUET_COMPRESSION = "write.parquet.compression-codec"
    ICE_TARGET_FILE_SIZE = "write.target-file-size-bytes"
    ICE_DISTRIBUTION_MODE = "write.distribution-mode"
    ICE_META_DELETE_AFTER_COMMIT = "write.metadata.delete-after-commit.enabled"
    ICE_META_PREV_VERSIONS_MAX = "write.metadata.previous-versions-max"
    ICE_FORMAT_VERSION = "format-version"

    TRUE = "true"
    FALSE = "false"
    APPEND = "append"
    FIELD = "field"
    TYPE = "type"